### PR TITLE
Corrected forcing data script and added function to run biomee multiple times

### PR DESCRIPTION
**Pull request by lauramarques**

### CODE REVIEW

**Comment by stineb** [comment]
Great you managed to get all checks passing! And great work on all the output variable additions. Just two small remaining points:

- `data/biomee_validation_2.rda`: how is this different to `data/biomee_validation.rda`? Can we keep just one of them?
- `data-raw/generate_biomee_driver_data_DBEN.R`: seems like this should be in the D-BEN repository, not in rsofun

Could you resolve this before I merge?

**Comment by lauramarques** [comment]
Yes, I will resolve these two points and I also need to add a couple of commits more needed to run the DBEN simulations.
Yes, my fork is up to date with geco-bern/rsofun:master.

**Comment by lauramarques** [comment]
I have now added the last commits and all checks have passed.
I have deleted `data-raw/generate_biomee_driver_data_DBEN.R`, and updated `data-raw/generate_biomee_driver_data.R`
I have removed the duplicate `data/biomee_validation.rda`. 
You can proceed with the merge now.

**Comment by stineb** [comment]
@lauramarques 
I've merged it but there were weird things happening in the merging. I'm resolving this now.
There is hard-coded stuff in there that seems D-BEN-specific ("Reset vegetation to initial conditions" in `biosphere_biomee`). I'm removing this now. Find a solution to specify the re-setting through modifying the model forcing.

Please remember, when adding code, using indenting.

**Comment by lauramarques** [comment]
Ok, I see.
The SR `reset_vegn_initial` only runs when `do_reset_veg` = TRUE in `params_siml`. We can specify this when preparing the drivers.

**Pull request merged**
