### PR TITLE
Homogenization 2.0

### PR DESCRIPTION
**Pull request by marcadella**
See issue #253 
+ fix negative N pools
+ improve numerical stability (preventing some segfaults from happening)
+ Fix reporting of some diagnostics that were missed.

### CODE REVIEW

**Comment by marcadella** [comment]
@fabern I haven't updated the documentation for P-model (point 4 in the old pull-request). I don't know p-model at all. I also completely re-written data_format.Rmd. To avoid back and forth, I propose that you just commit the changes you wish directly in this branch (253).

**Comment by fabern** [comment]
Thanks @marcadella, most of my suggested changes to the order of the docs were already done by you in commit (499b2c29087d0bfd27601bb5ef8ccce207c1dc5e), I now made small, last adjustments in (63f29b35d38f26bbe38e4ee2e5881ccb20c462bc).

This is ok so.

**Review by stineb — COMMENTED** [review]
Looks good from a quick glance. Thanks!

**Review by stineb — APPROVED** [review]
ok

**Pull request merged**
