### PR TITLE
Et data

### PR DESCRIPTION
**Pull request by jrmodel**
use the updated version

### CODE REVIEW

**Comment by khufkens** [comment]
Hi @stineb, should this be integrated now or how do we go about this. There don't seem to be any breaking changes (tests still pass - if not adjusted).

**Comment by stineb** [comment]
It's not clear to me what is new in the branch `jrmodel:ET_data` (looking at [this](https://github.com/jrmodel/rsofun-jr/commits/ET_data)). 

Whether to merge this or not depends on what we want to have in the rsofun documentation paper. If we keep the scope of that to using GPP and a "trait" (Vcmax) as calibration targets, then we should keep all ET-related developments out of the master branch for now. Therefore, I would not merge this now if it adds anything ET-related (but then, I can't see anything ET-related in commits to this branch).

**Comment by khufkens** [comment]
Fine with me. Will keep this open. @jrmodel keep your fork in sync (see sync button) to make this easier upstream if other changes to the main branch.
Screenshot from 2023-01-04 14-28-35

**Comment by jrmodel** [comment]
> Fine with me. Will keep this open. @jrmodel keep your fork in sync (see sync button) to make this easier upstream if other changes to the main branch. Screenshot from 2023-01-04 14-28-35

**Comment by jrmodel** [comment]
Ok. Fine

**Pull request closed without merging**
