### PR TITLE
Updates (mostly calibration-related).

### PR DESCRIPTION
**Pull request by stineb**

### CODE REVIEW

**Comment by khufkens** [comment]
@stineb 

There are quite some merge conflicts in the code. 
You will need to resolve them on your end I can not make that call.
So you will have to pull all historical changes into your branch, check out what is what and then the branch should be clean and then push directly to master from either a fork or your clone.

Screenshot from 2023-09-01 12-14-27

**Comment by stineb** [comment]
Indeed, I'll do that.

**Comment by khufkens** [comment]
Note, these issues are the reason I would argue that branches should be **short lived** and should address precise issues. The master has moved on, while cnmodel is out of sync.  Use a fork for larger refactoring, and branches for small patches, as this can be kept in sync more easily using the "Sync Fork" function in github.

Alternatively, you can merge the master into the branch, but again this becomes complicated as well.

**Comment by khufkens** [comment]
So, in short, @stineb FORK the current project. Then, apply the instructions above to merge conflicts correctly into master. Then, push back using a pull request. This gives the least chances of having things going bottom up.

**Comment by stineb** [comment]
My intention was actually to merge `master` into the `cnmodel` branch.  
The case here is that `cnmodel` is a different beast of a model altogether and may even warrant its own R function. But some fundamental decisions need to be taken before bringing pmodel and cnmodel together.

**Comment by khufkens** [comment]
That's your call, but don't break the current functional master. That's all I'm saying.

**Pull request closed without merging**
