### PR TITLE
Amends after CRAN feedback

### PR DESCRIPTION
**Pull request by pepaaran**
- Correct references in DESCRIPTION
- Remove `/dontrun` statements from docs
- Remove data from 2013 after speaking to Puechabon site responsibles
- Document inputs and outputs of the BiomeE functions

### CODE REVIEW

**Comment by pepaaran** [comment]
@khufkens @stineb 

I'm planning to submit this version of the package again to CRAN. Is everything from the copyright, licensing and authors side ready to go?

**Comment by khufkens** [comment]
@pepaaran from the licensing point of view everything is ok.

Makes sure to adjust your CRAN submission statement and the NEWS file according to the latest changes, including making the licensing more transparent.

The CRAN submission statement in particular must include how you addressed all comments made in the previous rejection of the package (as with peer review in science). If we didn't address an issue it has to be explained why as well (the motivation must hold).

Does this make sense?

**Comment by pepaaran** [comment]
Okay, thanks for the reminder. 

I added explanations of how we addressed the issues. Could one of you check it to make sure that the text about the copyright and so on is correct?

**Review by khufkens — APPROVED** [review]
still looks good

**Pull request merged**
